---
# tasks file for roles/install-apt-repo

- name: Install apt support packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - curl

- include_tasks: {{ ansible_os_family }}.yml
