---
# tasks file for roles/install-apt-repo
- name: Install apt support packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    
- name: Install GPG keys
  apt_key:
    id: "{{ item }}"
    state: present
    keyserver: pool.sks-keyservers.net
  with_items:
    - "{{ configured_apt_repositories[repository]['gpg_keys'] }}"

- name: Install {{ repository }} repository
  apt_repository:
    repo: "{{ configured_apt_repositories[repository]['url'] }}"
    state: present
    update_cache: true
    filename: "{{ repository }}"

- name: Run post install command
  shell: "{{ configured_apt_repositories[repository]['post_install_cmd'] }}"
  when: configured_apt_repositories[repository]['post_install_cmd'] is defined
  changed_when: false

